alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: default-receiver
      group_wait: 5s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
      - name: "null"
      - name: default-receiver
        webhook_configs:
          - url: http://alertmanager-webhook:9093/api/v1/alerts
            send_resolved: true

# Add custom scrape configs to monitor your Spring Boot app
prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'spring-boot-app'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            action: keep
            regex: spring-boot-app
          - source_labels: [__address__]
            action: replace
            regex: ([^:]+)(?::\d+)?
            replacement: $1:8080
            target_label: __address__
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name